prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix WUR_ont: <http://www.wur.nl/purl/ontology#>
prefix dct: <http://purl.org/dc/terms/>
prefix sio: <http://semanticscience.org/resource/>
prefix to: <http://purl.obolibrary.org/obo/TO#>
prefix WUR_acc: <http://www.wur.nl/purl/accession#>
prefix dbp: <http://dbpedia.org/property/>
prefix dct: <http://purl.org/dc/terms/>
prefix dbr: <http://dbpedia.org/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix om: <http://def.seegrid.csiro.au/ontology/om/om-lite#>
prefix ds1: <http://snowball:8890/DAV/home/papou001/rdf_sink/tomato_live.ttl>
prefix ds2: <http://snowball:8890/DAV/home/papou001/rdf_sink/Israel.ttl>
prefix ds3: <http://snowball:8890/DAV/home/papou001/rdf_sink/Netherlands.ttl>
prefix ds4: <http://snowball:8890/DAV/home/papou001/rdf_sink/Spain.ttl>
prefix ds5: <http://snowball:8890/DAV/home/papou001/rdf_sink/Belgium.ttl>
prefix ds6: <http://snowball:8890/DAV/home/papou001/rdf_sink/France.ttl>
prefix ds7: <http://snowball:8890/DAV/home/papou001/rdf_sink/MCPD.ttl>
prefix ds8: <http://snowball:8890/DAV/home/papou001/rdf_sink/sp_edit.ttl>

select (count(distinct ?acc) as ?numberOfSamples)
    #distinct ?acc ?pVal
where {
    ?acc a WUR_ont:id .
    ?orPlant WUR_ont:has_id ?acc .
    ?desPlant WUR_ont:descendant_of ?orPlant .

    ?exp a <http://purl.obolibrary.org/obo/AGRO_00000370> .
    ?exp <http://purl.obolibrary.org/obo/RO_0000057> ?desPlant .
    ?exp dbp:location ?country .
    ?exp sio:SIO_000219 ?obs .

    ?obs a om:observation .
    ?obs sio:SIO_000332 ?desPlant .
    ?obs to:has_phenotype_variable ?trait .
    ?trait a ?pVar .
    ?trait dct:title ?pTitle .
    ?trait to:has_phenotype_score ?pVal .

    VALUES ?country {<#country#>} .
    VALUES ?pTitle {"#phenotypeVariable#"} .
    VALUES ?pVal {"#phenotypeValue#"} .

    #VALUES ?country {dbr:Netherlands} .
    #VALUES ?pTitle {"Fruit color"} .
    #VALUES ?pVal {"5"} .
}
